php:
  preset: psr2
  risky: true
  enabled:
    - long_array_syntax
  disabled:
    - align_double_arrow
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    name: "*.php"
    not-name:
      - "*.blade.php"
      - "_ide_helper.php"
js:
  tab-width: 4
  use-tabs: false
  print-width: 120
  double-quotes: false
  trailing-commas: es5
  semicolons: true
  arrow-parens: always
  bracket-spacing: true
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    name:
      - "*.js"
      - "*.jsx"
    not-name:
      - "*.min.js"
css:
  tab-width: 4
  use-tabs: false
  print-width: 120
  double-quotes: false
  finder:
    exclude:
      - "modules"
      - "node_modules"
      - "storage"
      - "vendor"
    name:
      - "*.css"
      - "*.scss"
      - "*.less"