#!/usr/bin/env php
<?php
require(__DIR__ . '/app/bootstrap.php');

exit(($app = new \yii\console\Application(\yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/app/config/common.php'),
    require(__DIR__ . '/app/config/' . YII_ENV . '/common.php'),
    require(__DIR__ . '/app/config/cli.php'),
    require(__DIR__ . '/app/config/' . YII_ENV . '/cli.php')
)))->run());